# Generated by Django 2.2.7 on 2019-11-16 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Наименование продукта/услуги')),
                ('category', models.CharField(choices=[('food', 'Еда'), ('leisure', 'Развлечения'), ('household', 'Для дома'), ('hobby', 'Хобби'), ('other', 'Разное')], default='other', max_length=20, verbose_name='Категория')),
                ('description', models.TextField(blank=True, max_length=1500, null=True, verbose_name='Описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads', verbose_name='Изображение')),
            ],
        ),
    ]
